### ISSUE TITLE
Windows Build failure on KDDockWidgets binding

### ISSUE THREAD

**Issue by mkimberling** [KDAB/KDDockWidgets#267] opened 2021-12-27 18:57 UTC
Hello,

I'm trying to build for Windows with Visual Studio 2019 and encounter a build error for this build step.  I got it on both

[56/87] Running generator for KDDockWidgets binding...

I tried 1.5 and 1.4 and got the same error.

[build.log](https://github.com/KDAB/KDDockWidgets/files/7781429/build.log)

I'm trying to build the python bindings.  Here's how I configured the project:

cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DKDDockWidgets_STATIC=False -DKDDockWidgets_PYTHON_BINDINGS=True -DCMAKE_PREFIX_PATH=%QT_ROOT% -DCMAKE_INSTALL_PREFIX=..\kd_dock_widgets KDDockWidgets-1.5

-Matt

**Comment by winterz** [comment] 2021-12-27 19:29
this is probably the libclang.dll problem. 
The only solution we know is a hack to replace libclang.dll with the version provided by llvm.
For more information see near the bottom of README-bindings.md

excerpted here:
* On Windows the `libclang.dll` that ship with QtForPython is not compatible with MSVC2019.
  To fix this, copy the `libclang.dll` that comes with llvm into shiboken2, like so:

  ```
  cd C:\Python37\Lib\site-packages\shiboken2_generator
  copy libclang.dll libclang.dll.save
  copy "C:\Program Files\llvm\bin\libclang.dll" libclang.dll
  #Python3 installation in C:\Python37 and llvm in c:\Program Files\llvm. adjust as needed

**Comment by winterz** [comment] 2021-12-27 19:30
dupe of #187

**Closed by winterz** 2021-12-27 19:30 UTC

**Comment by k4sima** [comment] 2022-04-09 04:12
It seems that the build fails only when both "KDDockWidgets_QTQUICK" and "KDDockWidgets_PYTHON_BINDINGS" are ON.
If only one is ON, it will succeed. Do you know the cause?
