### ISSUE TITLE
lib/libkddockwidgets.so.1.4.95: undefined reference to `KDDockWidgets::staticMetaObject'

### ISSUE THREAD

**Issue by kishore-kkc** [KDAB/KDDockWidgets#226] opened 2021-08-18 08:11 UTC
Hi @iamsergio,

I'm getting below undefined reference error, while building example tests with command "cmake --build . "

bin/ld: lib/libkddockwidgets.so.1.4.95: undefined reference to `KDDockWidgets::staticMetaObject'

> nm lib/libkddockwidgets.so.1.4.95 | grep KDDockWidgets | grep staticMetaObject | grep U
                 U _ZN13KDDockWidgets16staticMetaObjectE

Configurations:
Qt: 5.15.2
Gcc 9.2.0
Cmake:3.9.0
ninja: 1.10.2

Thanks,
Kishore

**Comment by iamsergio** [comment] 2021-08-22 15:21
I can't reproduce this. Please remove any installed KDDW, remove any stale libraries, clean build and try again. If that doesn't work then paste here the exact commands used

**Comment by kishore-kkc** [comment] 2021-08-23 03:06
I have cleaned all the libraries and started a fresh but ended at same point. I'm getting this undefined reference error consistently.

Configurations:
> cat /etc/*release*
CentOS Linux release 7.6.1810 (Core)
> uname -a
Linux <machine_name> 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Qt: 5.15.2
Gcc 9.2.0
Cmake:3.9.0
ninja: 1.10.2

Below are the commands i have used:
1)synced code from: https://github.com/KDAB/KDDockWidgets.git
2) set CMAKE_PREFIX_PATH to qt5.15.2/lib/cmake
3) set PATH to ninja,gcc,cmake binaries
4)  cmake -G Ninja -DCMAKE_INSTALL_PREFIX=<build_path> .
5) cmake --build . 

I have even tried with below source code also, still i'm getting same issue.
https://github.com/KDAB/KDDockWidgets/releases/download/v1.4.0/kddockwidgets-1.4.0.tar.gz

Please let me know if you need any further details.

**Comment by winterz** [comment] 2021-08-23 14:02
I also cannot reproduce.
In the meantime, you could disable the examples by passing -DKDDockWidgets_EXAMPLES=False to cmake

**Comment by kishore-kkc** [comment] 2021-08-23 18:19
Hi @winterz ,

I have tried that option but that is not solving the problem, as i'm getting this undefined reference error if i use this library in other places.

I'm actually trying to compile hotspot tool, which has dependency on KDDockWidgets.

I'm wondering how it's reproducible only for me!!!, do we really have this symbol defined in gcc9.2.0 generated libraries? Can you check that in your build sandbox!
nm lib/libkddockwidgets.so.1.4.95 | grep KDDockWidgets | grep staticMetaObject | grep U
U _ZN13KDDockWidgets16staticMetaObjectE

or is there anyway i can get pre-compiled KDDockWidget libraries which can be directly used to build hotspot tool?

**Comment by winterz** [comment] 2021-08-23 21:19
nm -go lib/libkddockwidgets.so.1.4.95 | grep KDDockWidgets | grep staticMetaObject | grep U
says empty

```
% nm lib/libkddockwidgets.so.1.4.95 | grep KDDockWidgets | grep staticMetaObject
000000000011a860 D _ZN13KDDockWidgets10DockWidget16staticMetaObjectE
000000000011a760 D _ZN13KDDockWidgets10MainWindow16staticMetaObjectE
0000000000119fa0 D _ZN13KDDockWidgets11FrameWidget16staticMetaObjectE
000000000011a620 D _ZN13KDDockWidgets12DockRegistry16staticMetaObjectE
00000000001132c0 D _ZN13KDDockWidgets12LayoutWidget16staticMetaObjectE
0000000000113400 d _ZN13KDDockWidgets12StatePreDrag16staticMetaObjectE
0000000000119ea0 D _ZN13KDDockWidgets12TabBarWidget16staticMetaObjectE
000000000011a6e0 D _ZN13KDDockWidgets13MainWindowMDI16staticMetaObjectE
000000000011a3e0 D _ZN13KDDockWidgets13MultiSplitter16staticMetaObjectE
0000000000119f20 d _ZN13KDDockWidgets13SideBarButton16staticMetaObjectE
0000000000119ee0 D _ZN13KDDockWidgets13SideBarWidget16staticMetaObjectE
00000000001133c0 d _ZN13KDDockWidgets13StateDragging16staticMetaObjectE
000000000011a820 D _ZN13KDDockWidgets14DockWidgetBase16staticMetaObjectE
00000000001134c0 D _ZN13KDDockWidgets14DragController16staticMetaObjectE
000000000011a460 D _ZN13KDDockWidgets14FloatingWindow16staticMetaObjectE
000000000011a720 D _ZN13KDDockWidgets14MainWindowBase16staticMetaObjectE
000000000011a1e0 D _ZN13KDDockWidgets14NullIndicators16staticMetaObjectE
0000000000119f60 D _ZN13KDDockWidgets14QWidgetAdapter16staticMetaObjectE
0000000000119e20 D _ZN13KDDockWidgets14TitleBarWidget16staticMetaObjectE
000000000011a2a0 d _ZN13KDDockWidgets15IndicatorWindow16staticMetaObjectE
000000000011a420 D _ZN13KDDockWidgets15MDILayoutWidget16staticMetaObjectE
0000000000119e60 D _ZN13KDDockWidgets15TabWidgetWidget16staticMetaObjectE
000000000011a560 d _ZN13KDDockWidgets15WaylandMimeData16staticMetaObjectE
0000000000113500 D _ZN13KDDockWidgets16staticMetaObjectE
000000000011a220 D _ZN13KDDockWidgets17ClassicIndicators16staticMetaObjectE
000000000011a2e0 D _ZN13KDDockWidgets17CustomFrameHelper16staticMetaObjectE
000000000011a6a0 d _ZN13KDDockWidgets17LayoutGuestWidget16staticMetaObjectE
000000000011a5a0 d _ZN13KDDockWidgets19MinimalStateMachine16staticMetaObjectE
000000000011a1a0 D _ZN13KDDockWidgets19SegmentedIndicators16staticMetaObjectE
000000000011a320 D _ZN13KDDockWidgets19WidgetResizeHandler16staticMetaObjectE
000000000011a7a0 D _ZN13KDDockWidgets20DefaultWidgetFactory16staticMetaObjectE
0000000000119fe0 D _ZN13KDDockWidgets20FloatingWindowWidget16staticMetaObjectE
0000000000113340 d _ZN13KDDockWidgets20StateDraggingWayland16staticMetaObjectE
000000000011a7e0 D _ZN13KDDockWidgets22FrameworkWidgetFactory16staticMetaObjectE
000000000011a520 D _ZN13KDDockWidgets24DropAreaWithCentralFrame16staticMetaObjectE
0000000000113380 d _ZN13KDDockWidgets24StateInternalMDIDragging16staticMetaObjectE
000000000011a4a0 D _ZN13KDDockWidgets29DropIndicatorOverlayInterface16staticMetaObjectE
000000000011a660 d _ZN13KDDockWidgets5Debug11DebugWindow16staticMetaObjectE
0000000000113300 D _ZN13KDDockWidgets5Frame16staticMetaObjectE
000000000011a5e0 d _ZN13KDDockWidgets5State16staticMetaObjectE
0000000000119de0 d _ZN13KDDockWidgets6Button16staticMetaObjectE
000000000011a3a0 D _ZN13KDDockWidgets7SideBar16staticMetaObjectE
000000000011a4e0 D _ZN13KDDockWidgets8DropArea16staticMetaObjectE
000000000011a360 D _ZN13KDDockWidgets8TitleBar16staticMetaObjectE
000000000011a260 d _ZN13KDDockWidgets9Indicator16staticMetaObjectE
0000000000113480 d _ZN13KDDockWidgets9StateBase16staticMetaObjectE
0000000000113440 d _ZN13KDDockWidgets9StateNone16staticMetaObjectE
```

**Comment by iamsergio** [comment] 2021-08-23 21:38
strip "lib/cmake" from your CMAKE_PREFIX_PATH
alternatively just add Qt to PATH

if that doesn't help I'll try on a CentOS docker

**Comment by kishore-kkc** [comment] 2021-08-24 08:27
Hi @winterz ,

Can you trace below symbol with trace-symbol linker flag and show in which library this symbol is defined
0000000000113500 D _ZN13KDDockWidgets16staticMetaObjectE

Hi @iamsergio ,
I followed those steps and added Qt to PATH and stripped lib/cmake from CMAKE_PREFIX_PATH.
But it didn't work, still i'm getting the same issue.

**Comment by kishore-kkc** [comment] 2021-09-01 16:24
Hi @winterz @iamsergio ,

Could you please help!

**Comment by iamsergio** [comment] 2021-09-06 10:15
Closing as this is a problem in your environment, nobody else can repro.
I'll gladly investigate more, but I need quick access to the env where it's reproducible, ideally a Dockerfile

**Closed by iamsergio** 2021-09-06 10:15 UTC
