### ISSUE TITLE
Build error concerning KDBindings

### ISSUE THREAD

**Issue by arietto** [KDAB/KDDockWidgets#557] opened 2024-12-20 14:25 UTC
Hello! I am trying to build C++ app, which links to KDDockWidgets (v2.2.0) under Windows and Qt 5.15.2.
The library has been successfully built. But the consumer cannot be built due to missing KDBindings.lib.
How should I tweak KDDockWidgets build options in order to build KDBindings.lib?
Should I download external KDBindings repository?

**Comment by iamsergio** [comment] 2024-12-20 14:40
Hi, I can't reproduce the problem. Would you be able to attach a minimal main.cpp + CMakeLists.txt that shows it, then I'd be able to fix it

Are you installing KDDockWidgets (make install or equivalent), or using KDDW as a submodule ?

**Comment by arietto** [comment] 2024-12-23 08:10
I've got the following fragment in KDDockWidgetsTargets.cmake:
   ` set_target_properties(KDAB::kddockwidgets PROPERTIES
      INTERFACE_COMPILE_DEFINITIONS "KDDOCKWIDGETS_STATICLIB;KDDW_FRONTEND_QTWIDGETS;KDDW_FRONTEND_QT"
      INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/"
      INTERFACE_LINK_LIBRARIES "Qt5::Widgets;\$<LINK_ONLY:Qt5::WidgetsPrivate>;\$<LINK_ONLY:KDBindings>;    \$<LINK_ONLY:Qt5::GuiPrivate>;\$<LINK_ONLY:dwmapi>")`
I mean **LINK_ONLY:KDBindings** entry.

**Comment by iamsergio** [comment] 2024-12-24 10:56
try latest main branch, should be fixed

**Closed by iamsergio** 2024-12-24 10:56 UTC
