### ISSUE TITLE
Incorrectly redocking dock when `KDDockWidgets::MainWindowOption_HasCentralFrame` is used

### ISSUE THREAD

**Issue by delins** [KDAB/KDDockWidgets#245] opened 2021-09-29 00:10 UTC
I supply `KDDockWidgets::MainWindowOption_HasCentralFrame` to `KDDockWidgets::MainWindow` so that I can use `addDockWidgetAsTab`. This works, I can add docks as tabs. It has a weird side effect, however: if you programmatically add a dock using `addDockWidgetAsTab` and then drag-undock that tab to make it float, and then drag-redock it into the mainwindow, the end result is that the mainwindow's viewport is split between the dock that I created and some white canvas, which I assume is the `CentralFrame`. 

I can imagine why this default frame exists, but it should be ignored/hidden when an actual dock is redocked again.

**Comment by iamsergio** [comment] 2021-10-10 18:45
I can't reproduce this, with master

See the test I committed, it has instructions for running it, if you could change the code to make it repro it would be great, or tell me what I did wrong

**Comment by delins** [comment] 2021-10-11 23:12
Thanks for looking into this. I'll investigate this and my other issues further later this week

**Comment by delins** [comment] 2022-02-18 15:25
Is this something that can be fixed? I'm not trying to push people to fix this, but it would be helpful for me to know the status.

**Comment by iamsergio** [comment] 2022-09-05 21:11
Better late than never, this is fixed now

**Closed by iamsergio** 2022-09-05 21:11 UTC

**Comment by delins** [comment] 2022-09-05 21:28
Cool, thanks!
